/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Weather API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.vertin.eetweather.remote.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Temperatures are in Celsius scale.  Wind speed is given in m/s.  Phenomenon possible values: Clear, Few clouds, Variable clouds, Cloudy with clear spells, Cloudy, Light snow shower, Moderate snow shower, Heavy snow shower, Light shower, Moderate shower, Heavy shower, Light rain, Moderate rain, Heavy rain, Risk of glaze, Light sleet,Moderate sleet,Light snowfall, Moderate snowfall, Heavy snowfall, Snowstorm, Drifting snow, Hail, Mist, Fog, Thunder, Thunderstorm
 * @property phenomenon
 * @property tempmin
 * @property tempmax
 * @property text
 * @property sea
 * @property peipsi
 * @property places
 * @property winds
 */
@JsonClass(generateAdapter = true)
data class Day(
    @Json(name = "phenomenon") @field:Json(name = "phenomenon") var phenomenon: String? = null,
    @Json(name = "tempmin") @field:Json(name = "tempmin") var tempmin: Double? = null,
    @Json(name = "tempmax") @field:Json(name = "tempmax") var tempmax: Double? = null,
    @Json(name = "text") @field:Json(name = "text") var text: String? = null,
    @Json(name = "sea") @field:Json(name = "sea") var sea: String? = null,
    @Json(name = "peipsi") @field:Json(name = "peipsi") var peipsi: String? = null,
    @Json(name = "places") @field:Json(name = "places") var places: List<Place>? = null,
    @Json(name = "winds") @field:Json(name = "winds") var winds: List<Wind>? = null
)
