/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Weather API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.vertin.eetweather.remote.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property value
 * @property units
 */
@JsonClass(generateAdapter = true)
data class ElementWithUnit(
    @Json(name = "value") @field:Json(name = "value") var value: String? = null,
    @Json(name = "units") @field:Json(name = "units") var units: String? = null
)
