/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Weather API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.vertin.eetweather.remote.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property forecasts
 */
@JsonClass(generateAdapter = true)
data class ForecastsModel(
    @Json(name = "forecasts") @field:Json(name = "forecasts") var forecasts: List<Forecast>? = null
)
