/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Weather API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.vertin.eetweather.remote.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property code
 * @property name
 */
@JsonClass(generateAdapter = true)
data class Location(
    @Json(name = "code") @field:Json(name = "code") var code: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null
)
