/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Weather API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.vertin.eetweather.remote.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property timestamp
 * @property observations
 */
@JsonClass(generateAdapter = true)
data class ObservationsModel(
    @Json(name = "timestamp") @field:Json(name = "timestamp") var timestamp: String? = null,
    @Json(name = "observations") @field:Json(name = "observations") var observations: List<Station> = emptyList()
)
