/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Weather API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.vertin.eetweather.remote.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property name
 * @property phenomenon
 * @property tempmin
 * @property tempmax
 */
@JsonClass(generateAdapter = true)
data class Place(
    @Json(name = "name") @field:Json(name = "name") var name: String,
    @Json(name = "phenomenon") @field:Json(name = "phenomenon") var phenomenon: String? = null,
    @Json(name = "tempmin") @field:Json(name = "tempmin") var tempmin: Double? = null,
    @Json(name = "tempmax") @field:Json(name = "tempmax") var tempmax: Double? = null
)
