/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Weather API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.vertin.eetweather.remote.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property name
 * @property wmocode
 * @property longitude
 * @property latitude
 * @property phenomenon
 * @property visibility
 * @property precipitations
 * @property airpressure
 * @property relativehumidity
 * @property airtemperature
 * @property winddirection
 * @property windspeed
 * @property windspeedmax
 * @property waterlevel
 * @property waterlevelEh2000
 * @property watertemperature
 * @property uvindex
 */
@JsonClass(generateAdapter = true)
data class Station(
    @Json(name = "name") @field:Json(name = "name") var name: String="",
    @Json(name = "wmocode") @field:Json(name = "wmocode") var wmocode: String? = null,
    @Json(name = "longitude") @field:Json(name = "longitude") var longitude: String? = null,
    @Json(name = "latitude") @field:Json(name = "latitude") var latitude: String? = null,
    @Json(name = "phenomenon") @field:Json(name = "phenomenon") var phenomenon: String? = null,
    @Json(name = "visibility") @field:Json(name = "visibility") var visibility: String? = null,
    @Json(name = "precipitations") @field:Json(name = "precipitations") var precipitations: String? = null,
    @Json(name = "airpressure") @field:Json(name = "airpressure") var airpressure: String? = null,
    @Json(name = "relativehumidity") @field:Json(name = "relativehumidity") var relativehumidity: String? = null,
    @Json(name = "airtemperature") @field:Json(name = "airtemperature") var airtemperature: String? = null,
    @Json(name = "winddirection") @field:Json(name = "winddirection") var winddirection: String? = null,
    @Json(name = "windspeed") @field:Json(name = "windspeed") var windspeed: String? = null,
    @Json(name = "windspeedmax") @field:Json(name = "windspeedmax") var windspeedmax: String? = null,
    @Json(name = "waterlevel") @field:Json(name = "waterlevel") var waterlevel: String? = null,
    @Json(name = "waterlevel_eh2000") @field:Json(name = "waterlevel_eh2000") var waterlevelEh2000: String? = null,
    @Json(name = "watertemperature") @field:Json(name = "watertemperature") var watertemperature: String? = null,
    @Json(name = "uvindex") @field:Json(name = "uvindex") var uvindex: String? = null
)
