/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Weather API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.vertin.eetweather.remote.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property name
 * @property direction
 * @property speedmin
 * @property speedmax
 */
@JsonClass(generateAdapter = true)
data class Wind(
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "direction") @field:Json(name = "direction") var direction: String? = null,
    @Json(name = "speedmin") @field:Json(name = "speedmin") var speedmin: Double? = null,
    @Json(name = "speedmax") @field:Json(name = "speedmax") var speedmax: Double? = null
)
