version: 2.1
executors:
  main-executor:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      environment:
        JVM_OPTS: -Xmx3200m
jobs:
  build:
    executor: main-executor
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  test:
    executor: main-executor
    steps:
      -run:
        name: Run Tests
        command: ./gradlew lint test
      -store_artifacts:
        path: app/build/reports
        destination: reports
      -store_test_results:
        path: app/build/test-results
workflows:
  version: 2
  main_flow:
    jobs:
      - build
      - test

