version: 2.1
executors:
  main-executor:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
jobs:
  build:
    executor: main-executor
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: main-executor
    steps:
      - attach_workspace:
         at: .
      - run:
         name: Run Tests
         command: ./gradlew lint test
      - store_artifacts:
         path: app/build/reports
         destination: reports
      - store_test_results:
         path: app/build/test-results
workflows:
  version: 2
  main_flow:
    jobs:
      - build
      - test:
         requires:
           - build

