version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  checkout:
    executor: android/android-machine
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - "project"
  lint:
    executor: android/android-machine
    steps:
      - attach_workspace:
          at: ~/
      - run:
         name: lint
         command: ./gradlew lint
      - store_test_results:
         path: app/build/reports/lint-results.xml
  unit_tests:
    executor: android/android-machine
    steps:
      - attach_workspace:
          at: ~/
      - android/run-tests:
         test-command: ./gradlew testDebug
      - run:
         name: unit tests
         command: ./gradlew test

workflows:
  test-and-build:
    jobs:
      - checkout
      - lint:
         requires:
           - checkout
      - unit_tests:
         requires:
           - checkout
