version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  checkout:
    executor: android/android-machine
    steps:
      - checkout
      - run:
         name: ls
         command: ls /tmp


workflows:
  test-and-build:
    jobs:
      - checkout
